In [1]:
import pandas as pd

In [3]:
import pandas as pd

# Load data from CSV file
df = pd.read_csv('data/dvf.csv')

/tmp/ipykernel_201222/3711809370.py:4: DtypeWarning: Columns (2,4,5,9,10,12,13,14,16,17,18,19,20,21,22,23,24,25,26,27,28,29,31,32,37,38,39) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('data/dvf.csv')

In [4]:
df

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude,section_prefixe
0,2023-365614,2023-01-23,1,Vente,150000.0,NaN,NaN,EMPEYROU,B034,31530.0,...,NaN,NaN,T,terres,NaN,NaN,2160.0,1.189783,43.702895,0000C
1,2023-365614,2023-01-23,1,Vente,150000.0,NaN,NaN,EMPEYROU,B034,31530.0,...,NaN,NaN,T,terres,NaN,NaN,975.0,1.190073,43.702839,0000C
2,2023-367914,2023-02-17,1,Vente,1400.0,NaN,NaN,CODEVAL,B088,31620.0,...,NaN,NaN,L,landes,NaN,NaN,3950.0,1.370457,43.869089,0000M
3,2023-370895,2023-04-11,1,Vente,1800000.0,NaN,NaN,LA PEYROUSE,B099,31330.0,...,NaN,NaN,AB,terrains a bâtir,NaN,NaN,478.0,NaN,NaN,0000E
4,2023-370895,2023-04-11,1,Vente,1800000.0,NaN,NaN,LA PEYROUSE,B099,31330.0,...,NaN,NaN,AB,terrains a bâtir,NaN,NaN,478.0,NaN,NaN,0000E
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
424452,2021-486960,2021-12-31,1,Vente en l'état futur d'achèvement,977040.0,41.0,NaN,RUE GASTON DOUMERGUE,1820,31170.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.342996,43.584478,000AN
424453,2021-486960,2021-12-31,1,Vente en l'état futur d'achèvement,977040.0,41.0,NaN,RUE GASTON DOUMERGUE,1820,31170.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.342996,43.584478,000AN
424454,2021-486961,2021-12-29,1,Vente en l'état futur d'achèvement,216885.0,7.0,NaN,RUE D'AIX,0092,31400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.437264,43.578604,812AD
424455,2021-486961,2021-12-29,1,Vente en l'état futur d'achèvement,216885.0,7.0,NaN,RUE D'AIX,0092,31400.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.437264,43.578604,812AD
424456,2021-486962,2021-12-27,1,Vente,306190.0,6.0,NaN,RUE VALETTE,0380,31450.0,...,74.0,3.0,S,sols,NaN,NaN,276.0,1.515844,43.492191,000AE

In [7]:
df[df['numero_disposition'] == 'numero_disposition']

,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude,section_prefixe
50000,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude,section_prefixe
100001,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude,section_prefixe
150002,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude,section_prefixe
200003,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude,section_prefixe
250004,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude,section_prefixe
300005,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude,section_prefixe
350006,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude,section_prefixe
400007,id_mutation,date_mutation,numero_disposition,nature_mutation,valeur_fonciere,adresse_numero,adresse_suffixe,adresse_nom_voie,adresse_code_voie,code_postal,...,surface_reelle_bati,nombre_pieces_principales,code_nature_culture,nature_culture,code_nature_culture_speciale,nature_culture_speciale,surface_terrain,longitude,latitude,section_prefixe